JardinesEdti2022.Web/Controllers/AccesoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AutoMapper;
using JardinesEdi2022.Servicios.Facades;
using JardinesEdi2022.Utilidades;
using JardinesEdti2022.Web.Models.ViewModels.Cliente;

namespace JardinesEdti2022.Web.Controllers
{
    public class AccesoController : Controller
    {
        // GET: Acceso
        private readonly IUsuariosServicios _usuariosServicios;
        private readonly IPaisesServicios _paisesServicios;
        private readonly ICiudadesServicios _ciudadesServicios;

        private readonly IMapper _mapper;

        public AccesoController(IUsuariosServicios usuariosServicios, IPaisesServicios paisesServicios, ICiudadesServicios ciudadesServicios)
        {
            _usuariosServicios = usuariosServicios;
            _paisesServicios = paisesServicios;
            _ciudadesServicios = ciudadesServicios;
            _mapper = AutoMapperConfig.Mapper;
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string email, string clave)
        {
            var usuario = _usuariosServicios.GetUsuarioByEmail(email);
            if (usuario==null)
            {
                ViewBag.Error = "Usuario no registrado!!!";
                return View();
            }

            if (!usuario.Activo)
            {
                ViewBag.Error = "Usuario no activo!!!";
                return View();

            }
            string claveConvertida = HelperUsuario.ConvertirSha256(clave);
            if (usuario.Clave!=claveConvertida)
            {
                ViewBag.Error = "Clave errónea!!!";
                return View();

            }

            if (usuario.Reestablecer)
            {
                TempData["usuarioId"] = usuario.UsuarioId;
                return RedirectToAction("ResetPassword");
            }

            TempData["usuarioId"] = null;
            Session["usuario"] = usuario;
            FormsAuthentication.SetAuthCookie(usuario.Correo, false);

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            var clienteVm = new ClienteEditVm();
            clienteVm.Paises = _paisesServicios.GetLista().Select(p => new SelectListItem
            {
                Value = p.PaisId.ToString(),
                Text = p.NombrePais
            }).ToList();
            clienteVm.Ciudades = _ciudadesServicios.GetLista().Select(c => new SelectListItem
            {
                Value = c.CiudadId.ToString(),
                Text = c.NombreCiudad
            }).ToList();

            return View(clienteVm);
        }

        public ActionResult PasswordRecovery()
        {
            return View();
        }

        public ActionResult ResetPassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ResetPassword(string usuarioId, string clave, string nuevaClave, string confirmarClave)
        {
            var usuario = _usuariosServicios.GetUsuarioById(Convert.ToInt32(usuarioId));
            string claveConvertida = HelperUsuario.ConvertirSha256(clave);
            if (usuario.Clave!=claveConvertida)
            {
                ViewBag.Error = "Clave actual errónea!!!";
                TempData["usuarioId"] = usuario.UsuarioId;
                return View();
            }else if (nuevaClave!=confirmarClave)
            {
                ViewBag.Error = "La nueva clave y su confirmación no coinciden!!";
                TempData["usuarioId"] = usuario.UsuarioId;
                TempData["clave"] = clave;
                return View();
            }

            string nuevaClaveConvertida = HelperUsuario.ConvertirSha256(nuevaClave);
            usuario.Reestablecer = false;
            usuario.Clave = nuevaClaveConvertida;
            _usuariosServicios.Guardar(usuario);
            return RedirectToAction("Login");
        }

        public ActionResult CerrarSesion()
        {
            TempData["usuarioId"] = null;
            Session["usuario"] = null;
            FormsAuthentication.SignOut();
            return View("Login");
        }
    }
}

JardinesEdti2022.Web/Controllers/PaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using JardinesEdi2022.Entidades.Entidades;
using JardinesEdi2022.Servicios.Facades;
using JardinesEdti2022.Web.Models.ViewModels.Ciudad;
using JardinesEdti2022.Web.Models.ViewModels.Pais;
using PagedList;

namespace JardinesEdti2022.Web.Controllers
{
    public class PaisController : Controller
    {
        // GET: Pais
        private readonly IPaisesServicios _paisesServicios;
        private readonly ICiudadesServicios _ciudadesServicios;
        private readonly IMapper _mapper;

        public PaisController(IPaisesServicios paisesServicios, ICiudadesServicios ciudadesServicios)
        {
            _paisesServicios = paisesServicios;
            _ciudadesServicios = ciudadesServicios;
            _mapper = AutoMapperConfig.Mapper;
        }
        public ActionResult Index()
        {

            var listaPaisesVm = _mapper.Map<List<PaisListVm>>(_paisesServicios.GetLista());
            foreach (var paisListVm in listaPaisesVm)
            {
                paisListVm.CantidadCiudades = _ciudadesServicios.GetCantidad(paisListVm.PaisId);
            }

            return View(listaPaisesVm);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PaisEditVm paisVm)
        {
            if (!ModelState.IsValid)
            {
                return View(paisVm);
            }

            var pais = _mapper.Map<Pais>(paisVm);
            try
            {
                if (_paisesServicios.Existe(pais))
                {
                    ModelState.AddModelError(string.Empty, "País existente!!!");
                    return View(paisVm);
                }
                _paisesServicios.Guardar(pais);
                TempData["msg"] = "País agregado satisfactoriamente!!";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["error"] = "Error al intentar agregar un país";
                return RedirectToAction("Index");
            }
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var pais = _paisesServicios.GetEntityPorId(id.Value);
            if (pais == null)
            {
                return HttpNotFound("Código de país inexistente!!!");
            }

            var paisVm = _mapper.Map<PaisEditVm>(pais);
            return View(paisVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PaisEditVm paisVm)
        {
            if (!ModelState.IsValid)
            {
                return View(paisVm);
            }

            var pais = _mapper.Map<Pais>(paisVm);
            try
            {
                if (_paisesServicios.Existe(pais))
                {
                    ModelState.AddModelError(string.Empty, "País existente!!!");
                    return View(paisVm);
                }

                _paisesServicios.Guardar(pais);
                TempData["msg"] = "País editado satisfactoriamente!!";

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["error"] = "Error al intentar editar un país";
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var pais = _paisesServicios.GetEntityPorId(id.Value);
            if (pais == null)
            {
                return HttpNotFound("Código de país inexistente!!!");
            }

            var paisVm = _mapper.Map<PaisListVm>(pais);
            return View(paisVm);

        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            var pais = _paisesServicios.GetEntityPorId(id);
            try
            {
                if (_paisesServicios.EstaRelacionado(pais))
                {
                    ModelState.AddModelError(string.Empty, "País con registros relacionados... Baja denegada");
                    return View(_mapper.Map<PaisListVm>(pais));
                }
                _paisesServicios.Borrar(id);
                TempData["msg"] = "País eliminado satisfactoriamente!!";

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["error"] = "Error al intentar eliminar un país";
                return RedirectToAction("Index");
            }
        }

        public ActionResult Details(int? id, int? page)
        {
            var pageSize = 7;
            page = (page ?? 1);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var pais = _paisesServicios.GetEntityPorId(id.Value);
            if (pais == null)
            {
                return HttpNotFound("Código de país inexistente!!!");
            }

            var paisVm = new PaisDetailsVm()
            {
                Pais = _mapper.Map<PaisListVm>(pais),
                Ciudades = _mapper.Map<List<CiudadPaisDetailsVm>>(_ciudadesServicios.GetLista(pais.PaisId)).ToPagedList(page.Value,pageSize)
            };
            paisVm.Pais.CantidadCiudades = _ciudadesServicios.GetCantidad(pais.PaisId);
            return View(paisVm);
        }

        public ActionResult AddCity(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var pais = _paisesServicios.GetEntityPorId(id.Value);
            if (pais == null)
            {
                return HttpNotFound("Código de país inexistente!!!");
            }

            var listaPaises = _paisesServicios.GetLista();
            var PaisesDropDown = listaPaises.Select(p => new SelectListItem()
            {
                Text = p.NombrePais,
                Value = p.PaisId.ToString()
            }).ToList();
            var ciudadVm = new CiudadEditVm()
            {
                PaisId = id.Value,
                Paises = PaisesDropDown
            };
            return View(ciudadVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCity(CiudadEditVm ciudadVm)
        {
            if (!ModelState.IsValid)
            {
                var listaPaises = _paisesServicios.GetLista();
                var PaisesDropDown = listaPaises.Select(p => new SelectListItem()
                {
                    Text = p.NombrePais,
                    Value = p.PaisId.ToString()
                }).ToList();
                ciudadVm.Paises = PaisesDropDown;
                return View(ciudadVm);
            }

            var ciudad = _mapper.Map<Ciudad>(ciudadVm);
            try
            {
                if (_ciudadesServicios.Existe(ciudad))
                {
                    ModelState.AddModelError(string.Empty,"Ciudad existente!!!");
                    var listaPaises = _paisesServicios.GetLista();
                    var PaisesDropDown = listaPaises.Select(p => new SelectListItem()
                    {
                        Text = p.NombrePais,
                        Value = p.PaisId.ToString()
                    }).ToList();
                    ciudadVm.Paises = PaisesDropDown;
                    return View(ciudadVm);

                }
                _ciudadesServicios.Guardar(ciudad);
                return RedirectToAction($"Details/{ciudad.PaisId}");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, "Error al intentar agregar una Ciudad!!!");
                var listaPaises = _paisesServicios.GetLista();
                var PaisesDropDown = listaPaises.Select(p => new SelectListItem()
                {
                    Text = p.NombrePais,
                    Value = p.PaisId.ToString()
                }).ToList();
                ciudadVm.Paises = PaisesDropDown;
                return View(ciudadVm);
            }


        }

        public ActionResult EditCity(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var ciudad = _ciudadesServicios.GetEntityPorId(id.Value);
            if (ciudad == null)
            {
                return HttpNotFound("Código de ciudad erróneo!!!");
            }

            var ciudadVm = _mapper.Map<CiudadEditVm>(ciudad);
            var listaPaises = _paisesServicios.GetLista();

            var paisesDropDown = listaPaises.Select(p => new SelectListItem()
            {
                Text = p.NombrePais,
                Value = p.PaisId.ToString()
            }).ToList();
            ciudadVm.Paises = paisesDropDown;
            return View(ciudadVm);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCity(CiudadEditVm ciudadVm)
        {
            if (!ModelState.IsValid)
            {
                var listaPaises = _paisesServicios.GetLista();

                var paisesDropDown = listaPaises.Select(p => new SelectListItem()
                {
                    Text = p.NombrePais,
                    Value = p.PaisId.ToString()
                }).ToList();
                ciudadVm.Paises = paisesDropDown;

                return View(ciudadVm);
            }

            var ciudad = _mapper.Map<Ciudad>(ciudadVm);
            try

JardinesEdti2022.Web/Views/Shared/_Layout.cshtml
@using JardinesEdi2022.Entidades.Entidades
@using JardinesEdi2022.Utilidades
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Jardines App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="@Url.Action("Index","Home")">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("About","Home")">Acerca de</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Contact","Home")">Contacto</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Archivos
                        </a>
                        @if (Session["usuario"] != null)
                        {
                            if (((Usuario)Session["usuario"]).Rol == WC.AdminRole)
                            {
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="@Url.Action("Index","Pais")">Países</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index","Ciudad")">Ciudades</a></li>
                                    <li><div class="dropdown-divider"></div></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "Cliente")">Clientes</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "Proveedores")">Proveedores</a></li>
                                    <li><div class="dropdown-divider"></div></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "Categoria")">Categorias</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "Producto")">Productos</a></li>
                                </ul>

                            }
                            else
                            {
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="@Url.Action("IndexCustomer", "Categoria")">Categorias</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("IndexCustomer", "Producto")">Productos</a></li>
                                </ul>

                            }
                        }
                        else
                        {
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="@Url.Action("IndexCustomer", "Categoria")">Categorias</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("IndexCustomer", "Producto")">Productos</a></li>
                            </ul>


                        }
                    </li>
                </ul>
                <form class="d-flex">
                    @*Veo si el cliente no ha iniciado sesión, de ser así muestro el botón para que lo haga
                        caso contrario muestro el control para acceder al carrito y los datos del cliente logueado*@
                    @if (Session["usuario"] == null)
                    {
                        <a class="btn btn-outline-dark" aria-current="page" href="@Url.Action("LogIn", "Acceso")"><i class="fas fa-sign-out-alt me-1"></i>Iniciar Sesión</a>
                    }
                    else if (((Usuario)Session["usuario"]).Rol == WC.CustomerRole)
                    {
                        <a class="btn btn-outline-dark" href="@Url.Action("MostrarCarrito", "Carrito")">
                            <i class="fas fa-shopping-cart me-1"></i>
                            Carrito
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cantidadEnCarrito">0</span>
                        </a>

                        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#!"><b>@User.Identity.Name</b></a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("MisCompras", "Carrito")">Mis Compras</a></li>
                                    <li><hr class="dropdown-divider" /></li>
                                    <li><a class="dropdown-item" href="@Url.Action("CerrarSesion", "Acceso")">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#!"><b>@User.Identity.Name</b></a></li>
                                    <li><hr class="dropdown-divider" /></li>
                                    <li><a class="dropdown-item" href="@Url.Action("CerrarSesion", "Acceso")">Logout</a></li>
                                </ul>
                            </li>
                        </ul>

                    }
                </form>

            </div>
        </div>
    </nav>
    <div class="container body-content">
        @Html.Partial("_Notification")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<script>
    $(document).ready(function() {
        MostrarCantidadEnCarrito();
    });
    function MostrarCantidadEnCarrito() {
        //Pregunto si existe alguna etiqueta para mostrar la info del carrito
        if ($("#cantidadEnCarrito").length>0) {
            jQuery.ajax({
                "url": "@Url.Action("CantidadEnCarrito","Carrito")",
                "type": "GET",
                "dataType": "json",
                "contentType": "application/json; chartset=utf-8",
                success:function(data) {
                    $("#cantidadEnCarrito").text(data.cantidad);
                }
            });

        }
    }
</script>

JardinesEdti2022.Web/Views/Shared/_Notification.cshtml
@if (TempData["msg"] != null)
{

    <script src="~/Scripts/jquery-3.6.3.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["msg"]');


    </script>

}
@if (TempData["error"] != null)
{
    <script src="~/Scripts/jquery-3.6.3.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script type="text/javascript">

        toastr.error('@TempData["error"]');

    </script>

}