JardinesEdti2022.Web/Models/ViewModels/Carrito/CarritoFinalizarCompra.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JardinesEdti2022.Web.Models.ViewModels.Carrito
{
    public class CarritoFinalizarCompra
    {
        public List<CarritoListVm> ItemsCarrito { get; set; }

        [Required(ErrorMessage = "El país es requerido")]
        [Display(Name = "País")]
        [Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar un país")]
        public int PaisEnvioId { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar una ciudad")]
        [Display(Name = "Ciudad")]
        [Required(ErrorMessage = "La ciudad es requerida")]
        public int CiudadEnvioId { get; set; }
        [Display(Name = "Dirección")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(100, ErrorMessage = "El campo debe estar comprendido entre {1} y {2} caracteres", MinimumLength = 3)]

        public string DireccionEnvio { get; set; }
        [Display(Name = "Cod.Postal")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(10, ErrorMessage = "El campo debe estar comprendido entre {1} y {2} caracteres", MinimumLength = 3)]

        public string CodigoPostalEnvio { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(100, ErrorMessage = "El campo debe estar comprendido entre {1} y {2} caracteres", MinimumLength = 3)]
        [Display(Name = "Contacto")]

        public string ContactoEnvio { get; set; }
        [Display(Name = "Teléfono")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(20, ErrorMessage = "El campo debe estar comprendido entre {1} y {2} caracteres", MinimumLength = 3)]
        public string TelefonoEnvio { get; set; }

        public List<SelectListItem> Paises { get; set; }
        public List<SelectListItem> Ciudades { get; set; }


    }
}

JardinesEdti2022.Web/Models/ViewModels/Carrito/CarritoListVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JardinesEdti2022.Web.Models.ViewModels.Carrito
{
    public class CarritoListVm
    {
        public int CarritoId { get; set; }
        
        public int ProductoId { get; set; }
        public string Producto { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
        public decimal Total => Precio * Cantidad;

    }
}

JardinesEdti2022.Web/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using JardinesEdi2022.Entidades.Entidades;
using JardinesEdi2022.Entidades.Enums;
using JardinesEdi2022.Servicios.Facades;
using JardinesEdi2022.Utilidades;
using JardinesEdti2022.Web.Models.ViewModels.Carrito;

namespace JardinesEdti2022.Web.Controllers
{
    public class CarritoController : Controller
    {
        private readonly ICarritosServicios _carritosServicios;
        private readonly IPaisesServicios _paisesServicios;
        private readonly ICiudadesServicios _ciudadesServicios;
        private readonly IOrdenesServicios _ordenesServicios;
        private readonly IMapper _mapper;

        public CarritoController(ICarritosServicios carritosServicios, IPaisesServicios paisesServicios, ICiudadesServicios ciudadesServicios, IOrdenesServicios ordenesServicios)
        {
            _carritosServicios = carritosServicios;
            _paisesServicios = paisesServicios;
            _ciudadesServicios = ciudadesServicios;
            _ordenesServicios = ordenesServicios;
            _mapper = AutoMapperConfig.Mapper;
        }

        public ActionResult MostrarCarrito()
        {
            var clienteId = ((Usuario) Session["usuario"]).UsuarioId;
            try
            {
                var listaCarrito = _carritosServicios.GetItemsCarrito(clienteId);
                var listaCarritoVm = _mapper.Map<List<CarritoListVm>>(listaCarrito);
                return View(listaCarritoVm);
            }
            catch (Exception e)
            {
                TempData["Error"] = "Error al intentar acceder al carrito";
                return RedirectToAction("IndexCustomer","Producto");
            }
        }

        public JsonResult CantidadEnCarrito()
        {
            var clienteId = ((Usuario) Session["usuario"]).UsuarioId;
            var cantidad = _carritosServicios.CantidadEnCarrito(clienteId);
            return Json(new { cantidad = cantidad }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarAlCarrito(int productoId,string returnUrl)
        {
            var clienteId = ((Usuario)Session["usuario"]).UsuarioId;
            try
            {
                _carritosServicios.AgregarAlCarrito(clienteId,productoId,1);
                TempData["msg"] = "Producto agregado al carrito!!!";
                return Redirect(returnUrl);
            }
            catch (Exception e)
            {
                TempData["error"] = "Error al intentar agregar un producto al carrito!!!";
                return Redirect(returnUrl);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarAlCarritoMasDeUno(int productoId, int cantidad)
        {
            var clienteId = ((Usuario)Session["usuario"]).UsuarioId;
            try
            {
                _carritosServicios.AgregarAlCarrito(clienteId, productoId,cantidad);
                TempData["msg"] = "Producto agregado al carrito!!!";
                return RedirectToAction("MostrarCarrito");
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;
                return RedirectToAction("MostrarCarrito");
            }
        }

        public ActionResult QuitarDelCarrito(int productoId)
        {
            var clienteId = ((Usuario)Session["usuario"]).UsuarioId;
            try
            {
                _carritosServicios.QuitarDelCarrito(clienteId, productoId);
                TempData["msg"] = "Producto eliminado del carrito!!!";
                return RedirectToAction("MostrarCarrito");
            }
            catch (Exception e)
            {
                TempData["error"] = "Error al intentar quitar un producto del carrito!!!";
                return RedirectToAction("MostrarCarrito");
            }

        }

        public ActionResult CancelarCompra()
        {
            var clienteId = ((Usuario)Session["usuario"]).UsuarioId;
            try
            {
                _carritosServicios.VaciarCarrito(clienteId);
                
                return RedirectToAction("MostrarCarrito");
            }
            catch (Exception e)
            {
                TempData["error"] = "Error al intentar vaciar el carrito!!!";
                return RedirectToAction("MostrarCarrito");
            }

        }

        public ActionResult FinalizarCompra()
        {
            var clienteId = ((Usuario)Session["usuario"]).UsuarioId;
            var listaPaises = _paisesServicios.GetLista();
            var DropDownPaises = listaPaises.Select(p => new SelectListItem()
            {
                Text = p.NombrePais,
                Value = p.PaisId.ToString()
            }).ToList();
            var listaCiudades = _ciudadesServicios.GetLista();
            var DropDownCiudades = listaCiudades.Select(c => new SelectListItem()
            {
                Text = c.NombreCiudad,
                Value = c.CiudadId.ToString()
            }).ToList();

            var carritoVm = new CarritoFinalizarCompra()
            {
                ItemsCarrito = _mapper.Map<List<CarritoListVm>>(_carritosServicios.GetItemsCarrito(clienteId)),
                Paises = DropDownPaises,
                Ciudades = DropDownCiudades
            };
            return View(carritoVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FinalizarCompra(CarritoFinalizarCompra carritoVm)
        {
            var clienteId = ((Usuario)Session["usuario"]).UsuarioId;
            carritoVm.ItemsCarrito = _mapper.Map<List<CarritoListVm>>(_carritosServicios.GetItemsCarrito(clienteId));
            if (!ModelState.IsValid)
            {
                var listaPaises = _paisesServicios.GetLista();
                var DropDownPaises = listaPaises.Select(p => new SelectListItem()
                {
                    Text = p.NombrePais,
                    Value = p.PaisId.ToString()
                }).ToList();
                var listaCiudades = _ciudadesServicios.GetLista();
                var DropDownCiudades = listaCiudades.Select(c => new SelectListItem()
                {
                    Text = c.NombreCiudad,
                    Value = c.CiudadId.ToString()
                }).ToList();
                carritoVm.Paises = DropDownPaises;
                carritoVm.Ciudades = DropDownCiudades;

                return View(carritoVm);
            }
            //Si está todo OK entonces tengo que crear la orden con sus items
            //Creación del detalle de la orden
            List<DetalleOrden> detalleOrden = new List<DetalleOrden>();
            foreach (var itemCarrito in carritoVm.ItemsCarrito)
            {
                DetalleOrden dOrden = new DetalleOrden()
                {
                    ProductoId = itemCarrito.ProductoId,
                    Cantidad = itemCarrito.Cantidad,
                    PrecioUnitario = itemCarrito.Precio

                };
                detalleOrden.Add(dOrden);
            }
            //Creación de la Orden
            Orden orden = new Orden()
            {
                FechaCompra = DateTime.Now,
                PaisId = carritoVm.PaisEnvioId,
                CiudadId = carritoVm.CiudadEnvioId,
                Direccion = carritoVm.DireccionEnvio,
                CodigoPostal = carritoVm.CodigoPostalEnvio,
                Contacto = carritoVm.ContactoEnvio,
                Telefono = carritoVm.TelefonoEnvio,
                Total = detalleOrden.Sum(d => d.Cantidad * d.PrecioUnitario),
                ClienteId = clienteId,
                DetalleOrdenes = detalleOrden
            };
            try
            {
                /*Simular el cobro mediante un método
                 obteniendo el id de la transacción y el 
                estado de la misma, esto es, si fue aprobada o no*/
                Tuple<string, EstadoOrden> infoPago = HelperPago.ProcesarPago(orden.Total);
                orden.TransaccionId = infoPago.Item1;
                orden.EstadoOrden = infoPago.Item2;
                //Guardo la orden y sus items
                _ordenesServicios.Guardar(orden);
                ViewData["TransacciónId"] = orden.TransaccionId;
                ViewData["Estado"] = orden.EstadoOrden;
                return View("InformacionDelPago");


            }
            catch (Exception e)
            {
                ViewData["TransacciónId"] = orden.TransaccionId;
                ViewData["Estado"] = orden.EstadoOrden;
                return View("InformacionDelPago");
            }
        }

        [HttpGet]
        public JsonResult GetCiudades(int paisId)
        {
            var ciudades = _ciudadesServicios.GetLista(paisId).Select(c => new SelectListItem
            {
                Value = c.CiudadId.ToString(),
                Text = c.NombreCiudad
            }).ToList();

            return Json(ciudades, JsonRequestBehavior.AllowGet);
        }


        public ActionResult MisCompras()
        {
            var clienteId = ((Usuario) Session["usuario"]).UsuarioId;
            try
            {
                var listaOrdenes = _ordenesServicios.GetLista(clienteId);
                return View(listaOrdenes);
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;
                return View();
            }
        }
    }
}

JardinesEdti2022.Web/Views/Carrito/FinalizarCompra.cshtml
@model JardinesEdti2022.Web.Models.ViewModels.Carrito.CarritoFinalizarCompra
@{
    ViewBag.Title = "FinalizarCompra";
}

<h2>Finalizar Compra</h2>

<div class="container my-5">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="row">
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-flex justify-content-between">
                                        <h5 class="card-title">Detalle Carrito</h5>
                                        @Html.ActionLink("Seguir Comprando", "IndexCustomer", "Producto", null, new { @class = "btn btn-info" })
                                    </div>
                                    <table class="table table-bordered table-hover mt-3">
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.ItemsCarrito.FirstOrDefault().Producto)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.ItemsCarrito.FirstOrDefault().Cantidad)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.ItemsCarrito.FirstOrDefault().Precio)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.ItemsCarrito.FirstOrDefault().Total)
                                            </th>

                                            <th></th>
                                        </tr>
                                        @if (Model.ItemsCarrito.Any())
                                        {
                                            foreach (var item in Model.ItemsCarrito)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Producto)
                                                    </td>
                                                    <td style="text-align: right">
                                                        @Html.DisplayFor(modelItem => item.Cantidad)
                                                    </td>
                                                    <td style="text-align: right">
                                                        @Html.DisplayFor(modelItem => item.Precio)
                                                    </td>
                                                    <td style="text-align: right">
                                                        @Html.DisplayFor(modelItem => item.Total)
                                                    </td>

                                                    <td style="text-align: center">
                                                        @Html.ActionLink("Borrar", "QuitarDelCarrito", new { productoId = item.ProductoId }, new { @class = "btn btn-danger" })
                                                    </td>
                                                </tr>
                                            }
                                            <tr>
                                                <td><strong>TOTALES:</strong></td>
                                                <td style="text-align: right">@Model.ItemsCarrito.Sum(c => c.Cantidad)</td>
                                                <td colspan="2" style="text-align: right">@Model.ItemsCarrito.Sum(c => c.Precio * c.Cantidad).ToString("N2")</td>
                                                <td></td>
                                            </tr>

                                        }
                                        else
                                        {
                                            <tr>
                                                <td colspan="5" style="text-align: center" class="text-danger"><strong>Carrito sin productos</strong></td>
                                            </tr>
                                        }

                                    </table>

                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="col-sm-3">
                        <div class="row">
                            <div class="card">
                                <div class="card-body bg-light">
                                    <h5 class="card-title">Detalle Envío</h5>
                                    <form action="@Url.Action("FinalizarCompra", "Carrito")" method="post">
                                        @Html.AntiForgeryToken()
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.PaisEnvioId, new { @class = "form-label" })
                                            @Html.DropDownListFor(model => model.PaisEnvioId, Model.Paises, "Seleccione País", new { @class = "form-select" })
                                            @Html.ValidationMessageFor(model => model.PaisEnvioId, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.CiudadEnvioId, new { @class = "form-label" })
                                            @Html.DropDownListFor(model => model.CiudadEnvioId, Model.Ciudades, "Seleccione Ciudad", new { @class = "form-select" })
                                            @Html.ValidationMessageFor(model => model.CiudadEnvioId, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.DireccionEnvio, new { @class = "form-label" })
                                            @Html.TextBoxFor(model => model.DireccionEnvio, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.DireccionEnvio, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.CodigoPostalEnvio, new { @class = "form-label" })
                                            @Html.TextBoxFor(model => model.CodigoPostalEnvio, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.CodigoPostalEnvio, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ContactoEnvio, new { @class = "form-label" })
                                            @Html.TextBoxFor(model => model.ContactoEnvio, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.ContactoEnvio, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.TelefonoEnvio, new { @class = "form-label" })
                                            @Html.TextBoxFor(model => model.TelefonoEnvio, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.TelefonoEnvio, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="d-grid mt-3">
                                            <button type="submit" class="btn btn-success">
                                                <i class="fab fa-paypal"></i> Terminar y Procesar Pago
                                            </button>
                                        </div>


                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script>
        var cboPaises = document.getElementById("PaisEnvioId");
        cboPaises.addEventListener("change", LlenarComboCiudades);

        function LlenarComboCiudades() {
            fetch("@Url.Content("~/Carrito/GetCiudades")" + "?paisId=" + cboPaises.value)
                .then(function(result) {
                    if (result.ok) {
                        return result.json();
                    }
                })
                .then(function(data) {
                    var cboCiudades = document.getElementById("CiudadEnvioId");
                    cboCiudades.innerHTML = "";
                    data.forEach(function(elemento) {
                        let opt = document.createElement("option");
                        opt.appendChild(document.createTextNode(elemento.Text));
                        opt.value = elemento.Value;
                        cboCiudades.appendChild(opt);
                    });
                });
        }
    </script>
}

JardinesEdti2022.Web/Views/Carrito/InformacionDelPago.cshtml
@using JardinesEdi2022.Entidades.Enums

@{
    ViewBag.Title = "InformacionDelPago";
}

<h2>Pago Efectuado</h2>
<div class="row">
    <br/><br/>
    @{
        if ((EstadoOrden)ViewData["Estado"]==EstadoOrden.Aceptada)
        {
            <h1 class="text-success text-center">Gracias</h1>
            <i class="far fa-check-circle fa-9x text-success text-center"></i>
            <h2 class="text-success text-center">Su pago ha sido realizado con éxito</h2>
            <h4 class="text-center">ID de la transacción:@ViewData["TransaccionId"]</h4>
            <br/>
            <a href="@Url.Action("IndexCustomer","Producto")" class="btn btn-success">Volver</a>
        }
        else
        {
            <h1 class="text-danger text-center">Lo sentimos</h1>
            <i class="fas fa-exclamation-circle fa-9x text-danger text-center"></i>
            <h2 class="text-danger text-center">Su pago no pudo ser realizado</h2>
            <h4 class="text-center">ID de la transacción:@ViewData["TransaccionId"]</h4>
            <br/>
            <a href="@Url.Action("IndexCustomer","Producto")" class="btn btn-danger">Volver</a>

        }
    }
</div>

JardinesEdti2022.Web/Views/Carrito/MisCompras.cshtml
@using JardinesEdi2022.Utilidades
@model IEnumerable<JardinesEdi2022.Entidades.Entidades.Orden>
@{
    ViewBag.Title = "MisCompras";
}
<div class="container">
    <h2>Mis Compras</h2>
    <div class="row mt-5">
        <div class="col-sm-12">
            @if (Model.Any())
            {
                foreach (var orden in Model)
                {
                    <div class="row mb-3">
                        <div class="col-sm-12">
                            <div class="card bg-light">
                                <div class="card-title">
                                    <div class="d-flex justify-content-between">
                                        <label>Venta Nro.: @orden.OrdenId</label>
                                        <label>Fecha: @orden.FechaCompra.ToShortDateString()</label>
                                    </div>
                                    <div class="card-body bg-light">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th>Imágen</th>
                                                        <th>Producto</th>
                                                        <th>Precio</th>
                                                        <th>Cantidad</th>
                                                        <th>Sub-Total</th>
                                                    </tr>
                                                </thead>
                                                <tbody>

                                                    @foreach (var item in orden.DetalleOrdenes)
                                                    {
                                                        <tr>

                                                            @if (string.IsNullOrEmpty(item.Producto.Imagen))
                                                            {
                                                                <td>
                                                                    <img src="@Url.Content(WC.ProductImageFolder + WC.SinImagenDisponible)" style="width: 50px; height: 50px" />

                                                                </td>

                                                            }
                                                            else
                                                            {
                                                                <td>

                                                                    <img src="@Url.Content(WC.ProductImageFolder + item.Producto.Imagen)"  style="width: 50px; height: 50px" />
                                                                </td>

                                                            }
                                                            <td>
                                                                @item.Producto.NombreProducto
                                                            </td>
                                                            <td style="text-align: right">
                                                                @item.PrecioUnitario.ToString("N2")
                                                            </td>
                                                            <td style="text-align: right">@item.Cantidad.ToString("N2")</td>
                                                            <td style="text-align: right">@((item.Cantidad * item.PrecioUnitario).ToString("N2"))</td>
                                                        </tr>
                                                    }


                                                </tbody>
                                            </table>

                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <label>Total: @orden.Total</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="text-danger"> No se han registrado compras todavía</div>
            }
        </div>
    </div>
</div>

JardinesEdti2022.Web/Views/Carrito/MostrarCarrito.cshtml
@model IEnumerable<JardinesEdti2022.Web.Models.ViewModels.Carrito.CarritoListVm>

@{
    ViewBag.Title = "MostrarCarrito";
}
<div class="d-flex justify-content-between mt-3">
    <h2>Carrito</h2>
    <a href="@Url.Action("IndexCustomer","Producto")" class="btn btn-info">Seguir Comprando</a>
</div>

<table class="table table-bordered table-hover mt-3">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Producto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>

        <th></th>
    </tr>
    @if (Model.Any())
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto)
                </td>
                <td style="text-align: right">
                    @Html.DisplayFor(modelItem => item.Cantidad)
                </td>
                <td style="text-align: right">
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                <td style="text-align: right">
                    @Html.DisplayFor(modelItem => item.Total)
                </td>

                <td>
                    @Html.ActionLink("Borrar", "QuitarDelCarrito", new { productoId = item.ProductoId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
        <tr>
            <td><strong>TOTALES:</strong></td>
            <td style="text-align: right">@Model.Sum(c => c.Cantidad)</td>
            <td colspan="2" style="text-align: right">@Model.Sum(c => c.Precio * c.Cantidad).ToString("N2")</td>
            <td></td>
        </tr>

    }
    else
    {
        <tr>
            <td colspan="5" style="text-align: center" class="text-danger"><strong>Carrito sin productos</strong></td>
        </tr>
    }

</table>
@if (Model.Any())
{
    <div class="form-group">
        @Html.ActionLink("Finalizar Compra","FinalizarCompra",null,new{@class="btn btn-success"})
        @Html.ActionLink("Cancelar Compra","CancelarCompra",null,new {@class="btn btn-warning"})
    </div>
}